# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 84e32b647bd18332f35873777a72861d20bec590730b452c6e6cfd96b4c024106d0d4961f14ac611cd78ba11c6a556ebf8c413e5e63a28b3237cb5eee3b2dbfd

test:
  secret_key_base: a743bf24ebcf583178067117c6305fdaaa29c4b678318a698e30112002273f78fa65fb2f6fe2fe3b2e63ac8c02922079f8724b0ccb3de01ca8dae27811a9f623

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
